hl.window_rule({match={class=".*"}, suppress_event="maximize"})
hl.window_rule({match={title="^(Vesktop)$"}, opacity="0.95 0.85 override"})
hl.window_rule({match={title=".*Monkeytype.*"}, opacity="0.85"})
hl.window_rule({match={title=".*- he"}, opacity="0.90 0.80 override"})
hl.window_rule({match={title="^(Steam Settings)$"}, float=1})
hl.window_rule({match={title="^(Friends List)$"}, float=1})
hl.window_rule({match={title="^(Picture-in-Picture)$"}, float=1, pin=1, keep_aspect_ratio=1, opacity="1 override"})
hl.window_rule({match={class="^(gamescope)$"}, no_blur=1, fullscreen=1})
hl.window_rule({match={class="steam_app_.*"}, no_blur=1, fullscreen=1})
hl.window_rule({match={class="^(com.github.th-ch.youtube-music)$"}, opacity="0.75 0.65 override"})
hl.window_rule({match={title=".*- YouTube — Zen Browser"}, opacity="1 override"})
